plugins {
    alias(libs.plugins.android.application)
}

android {
    namespace 'com.security.droidguard'
    compileSdk {
        version = release(36) {
            minorApiLevel = 1
        }
    }

    buildFeatures {
        buildConfig = true
    }

    defaultConfig {
        applicationId "com.security.droidguard"
        minSdk 26
        targetSdk 36
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            // Real device
//            buildConfigField "String", "BASE_URL", "\"http://10.203.246.254:8081/api\""

            // Emulator
            buildConfigField "String", "BASE_URL", "\"http://10.0.2.2:8081/api\""
        }
        release {
            buildConfigField "String", "BASE_URL", "\"https://api.droidguard.io/api\""
            optimization {
                enable true
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_11
        targetCompatibility JavaVersion.VERSION_11
    }
}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    def room_version = "2.6.1"
    implementation "androidx.room:room-runtime:$room_version"
    annotationProcessor "androidx.room:room-compiler:$room_version"
    implementation "androidx.swiperefreshlayout:swiperefreshlayout:1.1.0"
}