spring.application.name=DroidGuardGateway

rabbitmq.analysis.queue=analysis.jobs.queue
rabbitmq.analysis.exchange=analysis.exchange
rabbitmq.analysis.routing-key=analysis.routingKey

file.storage.upload-dir=./storage/apks

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB

#spring.datasource.url=jdbc:sqlite:droidguard.db
#spring.datasource.driver-class-name=org.sqlite.JDBC
#spring.datasource.username=
#spring.datasource.password=
spring.datasource.url=jdbc:postgresql://db.omnawkudiedvqipfohtv.supabase.co:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.flyway.enabled=true

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

spring.jpa.hibernate.ddl-auto=validate

#spring.jpa.show-sql=true
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true