spring.application.name=DroidGuardGatewa

# RabbitMQ analysis queue configuration
rabbitmq.analysis.queue=analysis.jobs.queue
rabbitmq.analysis.exchange=analysis.exchange
rabbitmq.analysis.routing-key=analysis.routingKey

# DroidGuard storage configuration
file.storage.upload-dir=./storage/apks

# Spring Boot multipart configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=105MB

# MySQL Database Configuration
spring.datasource.url=jdbc:sqlite:droidguard.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=

# Hibernate / JPA Configuration
# Tells Hibernate exactly how to translate your Java Entities into SQLite SQL
spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect

# Automatically creates or updates the database tables
spring.jpa.hibernate.ddl-auto=update

# Formats the SQL in the console for easier debugging
spring.jpa.show-sql=true
#spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true